using AIAugmentedPitchAnalyzer.Application.Interfaces.IServices;
using System;
using System.Text.Json;
using System.Threading.Tasks;

namespace AIAugmentedPitchAnalyzer.Infrastructure.Services
{
    public class StubAIProvider : IAIProvider
    {
        public Task<IAIProviderResult> AnalyzeAsync(string prompt)
        {
            var summary = CreateSummary(prompt);
            var score = CalculateScore(prompt);
            var recommendations = CreateRecommendations(prompt);
            var analysisJson = JsonSerializer.Serialize(new
            {
                summary,
                score,
                recommendations,
                details = "This is a simulated analysis generated by a local provider.",
                generatedAt = DateTime.UtcNow
            });

            return Task.FromResult<IAIProviderResult>(new StubAIProviderResult(
                success: true,
                analysisJson: analysisJson,
                summary: summary,
                score: score,
                recommendations: recommendations));
        }

        private static string CreateSummary(string prompt)
        {
            if (string.IsNullOrWhiteSpace(prompt))
            {
                return "No pitch content was available to analyze.";
            }

            var lines = prompt.Replace("\r", string.Empty).Split('\n', StringSplitOptions.RemoveEmptyEntries);
            if (lines.Length <= 5)
            {
                return string.Join(" ", lines).Trim();
            }

            return string.Join(" ", lines[..Math.Min(6, lines.Length)]).Trim();
        }

        private static double CalculateScore(string prompt)
        {
            if (string.IsNullOrWhiteSpace(prompt))
            {
                return 0;
            }

            var length = prompt.Length;
            if (length < 200) return 40;
            if (length < 500) return 60;
            if (length < 1000) return 75;
            return 85;
        }

        private static string CreateRecommendations(string prompt)
        {
            return "Clarify the problem statement, strengthen the market validation, and include a clear business model. Ensure the pitch includes competitive differentiation and the next steps for customer acquisition.";
        }

        private sealed class StubAIProviderResult : IAIProviderResult
        {
            public StubAIProviderResult(bool success, string analysisJson, string summary, double score, string recommendations)
            {
                Success = success;
                AnalysisJson = analysisJson;
                Summary = summary;
                Score = score;
                Recommendations = recommendations;
            }

            public bool Success { get; }
            public string AnalysisJson { get; }
            public string Summary { get; }
            public double Score { get; }
            public string Recommendations { get; }
            public string? Message => null;
        }
    }
}
